public enum StatusName
{
    Bleeding,
    Poisoned,
    Entangled,
    Damage,
    ShellShocked,
    Blinded,
    Disadvantaged,
    Shocked,
    Boosted,
    Blocking,
    TacticalAdvantage,
    Resting,
    None,
    Enraged,
    Healing,
    BoostInitiative,
    BoostCombat,
    BoostAgillity,
    ModifyEndurance,
    ModifyPower
}
